<?php

/*
*
*	Expedia Services Connection
*
*
*/

//if (empty(arg(0)))
// 	expedia_services_test();
/**
 * Tests wsclient connections
 *
 *
 */
function expedia_services_test()
{
	if (module_exists('wsclient')):

        //Tarjeta de Prueba: VISA 4111111111111111 expiration 06 / 2016 CVC 737
	//Tarjeta de Prueba: CA 5401999999999999 expiration 11 / 2016 CVC 123

        $star = '06/01/2015';
        $end =  '06/05/2015';
        $hotelId = '109293';
        $roomTypeCode = '200730571';
        $rateCode = '203628677';
        $creditCardType = 'VI';
        $creditCardNumber = '4111111111111111';
        $creditCardIdentifier = '737';
        $creditCardExpirationMonth = '06';
        $creditCardExpirationYear = '2016';
        $firsName = 'test';
        $lastName = 'tester';
        $email = 'test@travelnow.com';
        $phone = '928000000';
	$rateKey = 'b2b46b0b-d98f-4548-807a-2ff139d1818a';
	$supplierType = 'E';
	$chargeableRate = '1912.48';
        $roomConfig = array();
        $roomConfig[] = array(
            'adults' => 2
        );


        //$codes = Hotel::GetHotelCodesByDestination(30);
        //$res = Expedia::GetHotelsByCode($codes['expedia'], $star, $end, $roomConfig);
        //dpm($res);
        //$res = Expedia::RoomAvailability($hotelId, $star, $end, $roomConfig);
        //dpm($res);

        //$res = Expedia::HotelBookReservation($hotelId, $star, $end, $roomConfig, $roomTypeCode,$rateCode, $rateKey, $supplierType, $chargeableRate, $firsName, $lastName,
        //    $email,$phone, $creditCardType, $creditCardNumber, $creditCardIdentifier, $creditCardExpirationMonth, $creditCardExpirationYear);
        //dpm($res);


        /*
		$res = Expedia::GetHotelInfo('238974');
		if (isset($res['HotelListResponse']) && isset($res['HotelListResponse']['EanWsError'])){
			$err = Expedia::GetErrorMessage($res);
		}
		else {
			dpm($res);
		}
		if (isset($err))
			dpm($err);
		*/
	endif;
}

/**
 * Implements hook_permission.
 */
function expedia_services_permission() {
  return array(
    'expedia_services module' => array(
      'title' => t('Expedia Services permission'),
  ));
}

/**
 * Implements hook_menu().
 */
function expedia_services_menu() {
	$items = array();
	$items['admin/config/services/expedia'] = array(
		'title' => 'Expedia Services Configuration',
		'description' => 'Configuration expedia services connection',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('expedia_services_form'),
		'access arguments' => array('expedia_services module'),
		'type' => MENU_NORMAL_ITEM,
	);

	return $items;
}

/**
 * Page callback: Expedia Services settings
 *
 * @see expedia_services_menu()
 */
function expedia_services_form($form, &$form_state) {

	// Sabre API group data
	$form['apidata'] = array(
		'#type' => 'fieldset',
		'#title' => t('Api Data'),
		'#collapsible' => FALSE,
		'#collapsed' => FALSE,
	);
	$form['apidata']['expedia_app_name'] = array(
		'#type'          => 'textfield',
		'#title'         => t('Expedia: Application name'),
		'#default_value' => variable_get('expedia_app_name'),
		'#description'   => t("Expedia app name."),
		'#required' => TRUE
	);
	$form['apidata']['expedia_client_id'] = array(
		'#type'          => 'textfield',
		'#title'         => t('Expedia: Client ID (CID)'),
		'#default_value' => variable_get('expedia_client_id'),
		'#description'   => t("Expedia client id."),
		'#required' => TRUE
	);
	$form['apidata']['expedia_key'] = array(
		'#type'          => 'textfield',
		'#title'         => t('Expedia: Key'),
		'#default_value' => variable_get('expedia_key'),
		'#description'   => t("Expedia app key."),
		'#required' => TRUE
	);
	$form['apidata']['expedia_shared_secret'] = array(
		'#type'          => 'textfield',
		'#title'         => t('Expedia: Shared secret'),
		'#default_value' => variable_get('expedia_shared_secret'),
		'#description'   => t("Expedia app shared secret."),
		'#required' => TRUE
	);
	// Fixed strings
	$form['apistrings'] = array(
		'#type' => 'fieldset',
		'#title' => t('Api Fixed Strings'),
		'#collapsible' => FALSE,
		'#collapsed' => FALSE,
	);
	$form['apistrings']['expedia_room_rate_disclaimer'] = array(
		'#type'          => 'textfield',
		'#title'         => t('Room rate disclaimer'),
		'#default_value' => variable_get('expedia_room_rate_disclaimer'),
		'#size' => 150, 
		'#maxlength' => 255, 
		'#description'   => t("You must display the room rate disclaimer below on all room availability pages. This text is not returned in the API."),
		'#required' => TRUE
	);
	$form['apistrings']['expedia_photos_disclaimer'] = array(
		'#type'          => 'textfield',
		'#title'         => t('EAN photos disclaimer'),
		'#default_value' => variable_get('expedia_photos_disclaimer'),
		'#size' => 150, 
		'#maxlength' => 255, 
		'#description'   => t("The disclaimer below must be included on any page containing EAN-sourced property photos."),
		'#required' => TRUE
	);

  return system_settings_form($form);
}
