<?php

/**
 * Implements hook_init().
 * CORS configuration for serving resources to extenal calls
 */
function feflip_features_init() {
	$method = $_SERVER['REQUEST_METHOD'];
	if (isset($_SERVER['HTTP_ORIGIN'])) {
		drupal_add_http_header('Access-Control-Allow-Origin', $_SERVER['HTTP_ORIGIN']);
	}
	if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS'])) {
		drupal_add_http_header('Access-Control-Allow-Headers', $_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS']);
	}
	if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD'])) {
		drupal_add_http_header('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
	}
	if ($method == 'OPTIONS') {
		exit;
	}
}

/**
 * Implements hook_admin_paths_alter().
 */
function feflip_features_admin_paths_alter(&$paths) {
  $paths['user'] = TRUE;
  $paths['user/*'] = TRUE;
}

/**
 * Implements hook_cron().
 */
function feflip_features_cron() {
	// Rss import task
	Helpers::ImportExternalRss();
}